fixtures:
  repositories:
  symlinks:
    stdlib: "#{source_dir}/modules/stdlib"
    sysctl: "#{source_dir}/modules/sysctl"
    ulimit: "#{source_dir}/modules/ulimit"
    os_performance: "#{source_dir}"
